# Traefik static configuration

log:
    level: ERROR

# Traefik Dashboard
api:
    insecure: true
    dashboard: true

entryPoints:
    web:
        address: ":80"
    web-secure:
        address: ":443"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        network: traefiknetwork

certificatesResolvers:
    letsencrypt: # Name of certresolver
        acme: 
            email: sergio.chumacero.fi@gmail.com
            storage: acme.json # Location in containter: /acme.json
            # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Staging LE Service
            tlsChallenge: {}
